[0m18:33:24.998078 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000285A3FAF0E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000285A3A6EF00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000285A383F380>]}


============================== 18:33:25.010836 | 29142d01-ba80-4e1e-9b85-d7c83e3d328b ==============================
[0m18:33:25.010836 [info ] [MainThread]: Running with dbt=1.10.6
[0m18:33:25.011837 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\chiranjit usa\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt init netflix', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:33:25.065738 [debug] [MainThread]: Starter project path: C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\venv\Lib\site-packages\dbt\include\starter_project
[0m18:33:25.132470 [info ] [MainThread]: 
Your new dbt project "netflix" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:33:25.134676 [info ] [MainThread]: Setting up your profile.
[0m18:36:52.079119 [error] [MainThread]: Encountered an error:

[0m18:36:52.127413 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\venv\Lib\site-packages\dbt\cli\requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\venv\Lib\site-packages\dbt\cli\requires.py", line 128, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\venv\Lib\site-packages\dbt\cli\main.py", line 483, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\venv\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\venv\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\venv\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\venv\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\venv\Lib\site-packages\dbt\task\init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\venv\Lib\site-packages\click\termui.py", line 168, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\venv\Lib\site-packages\click\termui.py", line 151, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m18:36:52.137935 [debug] [MainThread]: Command `dbt init` failed at 18:36:52.137935 after 207.34 seconds
[0m18:36:52.141558 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000285A3F70A70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000285A42C8F80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000285A63F6180>]}
[0m18:36:52.154388 [debug] [MainThread]: Flushing usage events
[0m18:36:52.493164 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:36:59.697195 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013D040B0BC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013D03DD0F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013D03EB5310>]}


============================== 18:36:59.704228 | 0bdb2c76-b466-40bb-8910-ba9be3f3cc0a ==============================
[0m18:36:59.704228 [info ] [MainThread]: Running with dbt=1.10.6
[0m18:36:59.704228 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\chiranjit usa\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init netflix', 'send_anonymous_usage_stats': 'True'}
[0m18:36:59.733514 [info ] [MainThread]: A project called netflix already exists here.
[0m18:36:59.735795 [debug] [MainThread]: Command `dbt init` succeeded at 18:36:59.734785 after 0.22 seconds
[0m18:36:59.735795 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013D0459B590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013D04435100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013D00B1EE70>]}
[0m18:36:59.736795 [debug] [MainThread]: Flushing usage events
[0m18:36:59.920590 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:37:49.563753 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027847C48CE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027847E687A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278477E3C20>]}


============================== 18:37:49.570061 | e7c7748b-153a-49ae-bfb4-89700d8861e0 ==============================
[0m18:37:49.570061 [info ] [MainThread]: Running with dbt=1.10.6
[0m18:37:49.570061 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\chiranjit usa\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init netflix', 'send_anonymous_usage_stats': 'True'}
[0m18:37:49.595293 [debug] [MainThread]: Starter project path: C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\venv\Lib\site-packages\dbt\include\starter_project
[0m18:37:49.625514 [info ] [MainThread]: 
Your new dbt project "netflix" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:37:49.627080 [info ] [MainThread]: Setting up your profile.
[0m18:39:19.293769 [info ] [MainThread]: Profile netflix written to C:\Users\chiranjit usa\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m18:39:19.296030 [debug] [MainThread]: Command `dbt init` succeeded at 18:39:19.294767 after 89.90 seconds
[0m18:39:19.296030 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278472DA450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278479B0560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027849F10B00>]}
[0m18:39:19.296030 [debug] [MainThread]: Flushing usage events
[0m18:39:19.605343 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:42:53.252369 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A1468BD7F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A14A2618B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A14986B140>]}


============================== 23:42:53.260100 | 5597e17c-b35e-4a8c-9f61-bd347cfaf1ff ==============================
[0m23:42:53.260100 [info ] [MainThread]: Running with dbt=1.10.6
[0m23:42:53.261100 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\chiranjit usa\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt test', 'send_anonymous_usage_stats': 'True'}
[0m23:42:53.262609 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:42:53.263801 [debug] [MainThread]: Command `dbt test` failed at 23:42:53.263801 after 0.18 seconds
[0m23:42:53.263801 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A14A0D6E40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A1468BD7F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A14A5C81D0>]}
[0m23:42:53.264814 [debug] [MainThread]: Flushing usage events
[0m23:42:53.538059 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:43:03.154142 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFAEDCBC20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFAF935BE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFB1D418B0>]}


============================== 23:43:03.158167 | 143942a5-b673-4e94-84e3-66e6c475b11f ==============================
[0m23:43:03.158167 [info ] [MainThread]: Running with dbt=1.10.6
[0m23:43:03.159164 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\chiranjit usa\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt test', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:43:03.159164 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\chiranjit usa\OneDrive - Northeastern University\Attachments\Desktop\data engineering projects\netflix-snowflake-dbt-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:43:03.161425 [debug] [MainThread]: Command `dbt test` failed at 23:43:03.160425 after 0.12 seconds
[0m23:43:03.161425 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFB1A215B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFB12C5E80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FFB20A98B0>]}
[0m23:43:03.162425 [debug] [MainThread]: Flushing usage events
[0m23:43:03.466963 [debug] [MainThread]: An error was encountered while trying to flush usage events
